{{- if .Values.worker.enabled }}
{{- range $i, $job := .Values.worker.cronjobs }}
{{- if $job.enabled }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ include "ifrcgo-risk-module.fullname" $ }}-{{ $i | nospace | lower | replace "_" "-" }}"
  labels:
    app.kubernetes.io/name: {{ include "ifrcgo-risk-module.fullname" $ }}
    app.kubernetes.io/component: {{ include "ifrcgo-risk-module.fullname" $ }}-api-jobs
    environment: {{ $.Values.environment }}
    release: {{ $.Release.Name }}
spec:
  schedule: {{ $job.schedule | quote }}
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      activeDeadlineSeconds: {{ default 7200 $job.timeLimit }} # 2 hours default TODO: Lower this
      template:
        spec:
          restartPolicy: "Never"
          {{- with $.Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: "{{ include "ifrcgo-risk-module.fullname" $ }}-{{ $i | nospace | lower | replace "_" "-" }}"
              image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
              command: ["./manage.py", "{{ $i }}"]
              resources:
                requests:
                  cpu: {{ default $.Values.worker.defaultResources.requests.cpu $job.requestsCpu }}
                  memory: {{ default $.Values.worker.defaultResources.requests.memory $job.requestsMemory }}
                limits:
                  cpu: {{ default $.Values.worker.defaultResources.limits.cpu $job.limitsCpu }}
                  memory: {{ default $.Values.worker.defaultResources.limits.memory $job.limitsMemory }}
              envFrom:
                - configMapRef:
                    name: {{ include "ifrcgo-risk-module.fullname" $ }}-api-configmap
                - secretRef:
                    name: {{ include "ifrcgo-risk-module.secretname" $ }}

{{- end }}

{{- end }}

{{- end }}