version: "3.7"

services:
  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_DATABASE=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/redis_data

  server:
    build: .
    env_file:
      - .env
    command: bash -c "/code/scripts/run_develop.sh"
    volumes:
      - .:/code
    ports:
      - "9001:9001"
    depends_on:
      - db
      - redis

volumes:
  postgres-data:
  redis-data:
