version: "3.7"

services:
  db:
    image: postgres:12.0-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DATABASE=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis-data:/redis_data

  titiler:
    image: developmentseed/titiler:latest
    environment:
      - PORT=9008
        #- FORWARDED_ALLOW_IPS="*"
        #- GDAL_HTTP_MAX_RETRY=3
        #- CPL_VSIL_CURL_ALLOWED_EXTENSIONS=".tif"
        #- GDAL_HTTP_UNSAFESSL=YES
    ports:
      - "9008:9008"

  server:
    build: .
    env_file:
      - .env
    restart: unless-stopped
    command: bash -c "/code/scripts/run_prod.sh"
    volumes:
      - .:/code
      - ./risk-storage/server/static:/code/staticfiles
      - ./risk-storage/server/media:/code/media           
    ports:
      - "9007:9007"
    depends_on:
      - db
      - redis
  
  nginx:
    image: nginx:1.21
    user: root
    volumes:
      # Nginx config
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Static files
      - ./risk-storage/server/static:/app-assests/server-static:ro
      # Media files
      - ./risk-storage/server/media:/app-assests/server-media:ro
    restart: unless-stopped
    ports:
      - '8002:80'
    depends_on:
      - server
volumes:
  postgres-data:
  redis-data:
