# Generated by Django 3.2.11 on 2022-01-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=255, null=True, verbose_name="name")),
                ("iso3", models.CharField(blank=True, max_length=3, null=True, verbose_name="iso3")),
                ("iso", models.CharField(blank=True, max_length=2, null=True, verbose_name="iso3")),
            ],
        ),
    ]
