# Generated by Django 3.2.13 on 2022-04-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_region_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='bbox',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='bbox'),
        ),
    ]
