# Generated by Django 3.2.13 on 2022-05-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_country_bbox"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="centroid",
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name="centroid"),
        ),
    ]
