# Generated by Django 3.2.16 on 2023-02-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_country_centroid'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='independent',
            field=models.BooleanField(default=None, help_text='Is this an independent country?', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='is_deprecated',
            field=models.BooleanField(default=False, help_text='Is this an active, valid country?'),
        ),
    ]
