# Generated by Django 3.2.11 on 2022-02-07 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seasonal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idmc',
            name='country',
        ),
    ]
