# Generated by Django 3.2.13 on 2022-05-17 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_country_bbox"),
        ("seasonal", "0007_auto_20220506_0636"),
    ]

    operations = [
        migrations.CreateModel(
            name="GarProbabilistic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "hazard_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EQ", "Earthquake"),
                            ("FL", "Flood"),
                            ("TC", "Cyclone"),
                            ("EP", "Epidemic"),
                            ("FI", "Food Insecurity"),
                            ("SS", "Storm Surge"),
                            ("DR", "Drought"),
                            ("TS", "Tsunami"),
                            ("CD", "Cyclonic Wind"),
                        ],
                        max_length=100,
                        verbose_name="hazard type",
                    ),
                ),
                ("absolute_loss_in_million", models.FloatField(blank=True, null=True, verbose_name="Absolute loss in Million")),
                ("capital_stock_percentage", models.FloatField(blank=True, null=True, verbose_name="Capital stock percentage")),
                ("gfcf", models.FloatField(blank=True, null=True, verbose_name="GFCF")),
                ("social_exp", models.FloatField(blank=True, null=True, verbose_name="Social Exp")),
                ("total_revenue", models.FloatField(blank=True, null=True, verbose_name="Total Revenue")),
                ("gross_saving", models.FloatField(blank=True, null=True, verbose_name="Gross Saving")),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.country",
                        verbose_name="country",
                    ),
                ),
            ],
        ),
    ]
