# Generated by Django 3.2.13 on 2022-05-18 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_country_bbox"),
        ("seasonal", "0009_possibleearlyactions"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublishReportProgram",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateTimeField(blank=True, null=True, verbose_name="Start Date")),
                ("end_date", models.DateTimeField(blank=True, null=True, verbose_name="End Date")),
                ("inactive", models.BooleanField(blank=True, null=True, verbose_name="Inactive")),
                ("program_name", models.CharField(max_length=255, verbose_name="Program Name")),
                ("program_manager", models.CharField(max_length=255, verbose_name="Program Manager")),
                ("area", models.CharField(blank=True, max_length=255, null=True, verbose_name="Area")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Description")),
                ("communities", models.TextField(blank=True, null=True, verbose_name="Communities")),
                ("bread_cumbs", models.TextField(blank=True, null=True, verbose_name="Bread Cumbs")),
                ("accuracy_level", models.CharField(blank=True, max_length=255, null=True, verbose_name="Accuracy")),
                ("community_engagement", models.TextField(blank=True, null=True, verbose_name="Community Engagement")),
                ("measurement_assignment", models.TextField(blank=True, null=True, verbose_name="Measurement Assignment")),
                ("community_vca", models.TextField(blank=True, null=True, verbose_name="Community VCA")),
                (
                    "country",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="common.country", verbose_name="Country"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublishReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("report_name", models.CharField(max_length=255, verbose_name="Report Name")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Description")),
                ("email", models.CharField(blank=True, max_length=255, null=True, verbose_name="Email")),
                ("attachment_name", models.CharField(blank=True, max_length=255, null=True, verbose_name="Attachment Name")),
                ("attachment", models.CharField(blank=True, max_length=255, null=True, verbose_name="Attachment")),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="seasonal.publishreportprogram",
                        verbose_name="Program Name",
                    ),
                ),
            ],
        ),
    ]
