# Generated by Django 3.2.13 on 2022-05-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasonal', '0010_publishreport_publishreportprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='possibleearlyactions',
            name='effective_time_raw',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Effective Time Raw'),
        ),
        migrations.AddField(
            model_name='possibleearlyactions',
            name='implementation_date_raw',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Implementation Date Raw'),
        ),
        migrations.AddField(
            model_name='possibleearlyactions',
            name='timeframe_raw',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Timeframe Raw'),
        ),
    ]
