# Generated by Django 3.2.13 on 2022-06-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seasonal", "0012_auto_20220620_0947"),
    ]

    operations = [
        migrations.AddField(
            model_name="publishreport",
            name="attachment_url",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Attachment URL"),
        ),
        migrations.AddField(
            model_name="publishreport",
            name="publish_report_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Publish Report"),
        ),
    ]
