# Generated by Django 3.2.16 on 2022-11-17 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_country_centroid'),
        ('seasonal', '0013_auto_20220622_0531'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard_type', models.CharField(blank=True, choices=[('EQ', 'Earthquake'), ('FL', 'Flood'), ('TC', 'Cyclone'), ('EP', 'Epidemic'), ('FI', 'Food Insecurity'), ('SS', 'Storm Surge'), ('DR', 'Drought'), ('TS', 'Tsunami'), ('CD', 'Cyclonic Wind')], max_length=100, verbose_name='hazard type')),
                ('january', models.FloatField(blank=True, null=True, verbose_name='january')),
                ('february', models.FloatField(blank=True, null=True, verbose_name='february')),
                ('march', models.FloatField(blank=True, null=True, verbose_name='march')),
                ('april', models.FloatField(blank=True, null=True, verbose_name='april')),
                ('may', models.FloatField(blank=True, null=True, verbose_name='may')),
                ('june', models.FloatField(blank=True, null=True, verbose_name='june')),
                ('july', models.FloatField(blank=True, null=True, verbose_name='july')),
                ('august', models.FloatField(blank=True, null=True, verbose_name='august')),
                ('september', models.FloatField(blank=True, null=True, verbose_name='september')),
                ('october', models.FloatField(blank=True, null=True, verbose_name='october')),
                ('november', models.FloatField(blank=True, null=True, verbose_name='november')),
                ('december', models.FloatField(blank=True, null=True, verbose_name='december')),
                ('yearly_sum', models.FloatField(blank=True, null=True, verbose_name='yearly_sum')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.country', verbose_name='country')),
            ],
        ),
    ]
