# Generated by Django 3.2.17 on 2023-09-09 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0007_auto_20230206_0403"),
        ("seasonal", "0017_auto_20230717_1354"),
    ]

    operations = [
        migrations.CreateModel(
            name="GwisSeasonal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "hazard_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EQ", "Earthquake"),
                            ("FL", "Flood"),
                            ("TC", "Cyclone"),
                            ("EP", "Epidemic"),
                            ("FI", "Food Insecurity"),
                            ("SS", "Storm Surge"),
                            ("DR", "Drought"),
                            ("TS", "Tsunami"),
                            ("CD", "Cyclonic Wind"),
                            ("WF", "WildFire"),
                        ],
                        max_length=100,
                        verbose_name="hazard type",
                    ),
                ),
                ("january", models.FloatField(blank=True, null=True, verbose_name="january")),
                ("february", models.FloatField(blank=True, null=True, verbose_name="february")),
                ("march", models.FloatField(blank=True, null=True, verbose_name="march")),
                ("april", models.FloatField(blank=True, null=True, verbose_name="april")),
                ("may", models.FloatField(blank=True, null=True, verbose_name="may")),
                ("june", models.FloatField(blank=True, null=True, verbose_name="june")),
                ("july", models.FloatField(blank=True, null=True, verbose_name="july")),
                ("august", models.FloatField(blank=True, null=True, verbose_name="august")),
                ("september", models.FloatField(blank=True, null=True, verbose_name="september")),
                ("october", models.FloatField(blank=True, null=True, verbose_name="october")),
                ("november", models.FloatField(blank=True, null=True, verbose_name="november")),
                ("december", models.FloatField(blank=True, null=True, verbose_name="december")),
                ("yearly_sum", models.FloatField(blank=True, null=True, verbose_name="yearly_sum")),
                (
                    "country",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="common.country", verbose_name="country"),
                ),
            ],
        ),
    ]
