# Generated by Django 3.2.8 on 2022-01-03 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0011_auto_20211209_1003'),
        ('earthquake', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earthquake',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ipc.country', verbose_name='country'),
        ),
    ]
