---
# Source: ifrcgo-risk-module-helm/charts/app/templates/config/secret.yaml
kind: Secret
apiVersion: v1
metadata:
  name: risk-1-secret
  labels:
    app: risk-1
    environment: ALPHA-1
    release: release-name
type: Opaque
stringData:
  # secrets
  DJANGO_SECRET_KEY: "xyz"
  METEOSWISS_S3_ACCESS_KEY: "dummy-access-key"
  METEOSWISS_S3_BUCKET: "dummy-bucket"
  METEOSWISS_S3_ENDPOINT_URL: "https://dummy.endpoint"
  METEOSWISS_S3_SECRET_KEY: "dummy-secret-key"
  PDC_ACCESS_TOKEN: "dummy-token"
  PDC_PASSWORD: "dummy-password"
  PDC_USERNAME: "dummy-username"
  SENTRY_DSN: "https://xyz@sentry.local.example.com/14"

---
# Source: ifrcgo-risk-module-helm/charts/app/templates/config/configmap.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: risk-1-env-name
  labels:
    app: risk-1
    environment: ALPHA-1
    release: release-name
data:
  # Configs
  APPS_LOGGING_LEVEL: "WARNING"
  CACHE_REDIS_URL: "redis://risk-module-dragonfly:6379/0"
  CELERY_REDIS_URL: "redis://risk-module-dragonfly:6379/1"
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_DEBUG: "false"
  DJANGO_TIME_ZONE: "UTC"
  RISK_API_FQDN: "risk-api-1.ifrcgo.local.example.com"
  RISK_ENVIRONMENT: "ALPHA-1"
  RISK_RELEASE: "develop.xxxxxxxx"
  SENTRY_PROFILE_SAMPLE_RATE: "0.8"
  SENTRY_TRACE_SAMPLE_RATE: "0.8"
  TIME_ZONE: "UTC"

---
# Source: ifrcgo-risk-module-helm/charts/app/templates/hooks/job.yaml
# Hook files ConfigMap for: create-users
apiVersion: v1
kind: ConfigMap
metadata:
  name: risk-1-create-users-files
  annotations:
    argocd.argoproj.io/hook: "Sync"
    argocd.argoproj.io/sync-wave: "25"
    # Refresh content on every sync and clean up before the next run.
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  labels:
    app: risk-1
    component: hook
    hookName: create-users
    environment: ALPHA-1
    release: release-name
data:
  create_users.py: "import os\nfrom django.contrib.auth import get_user_model\nfrom django.db import transaction\n\nUser = get_user_model()\n\nuser_credentials = [\n    user_credential.split(\":\")\n    for user_credential in os.environ[\"ADMIN_USER_EMAIL_PASSWORD_SET\"].split(\",\")\n]\n\nprint(\"Parsed provided credentials:\", user_credentials)\n\n@transaction.atomic\ndef create_initial_users(user_credentials):\n    for first_name, last_name, username, email, password_hash in user_credentials:\n        user, created = User.objects.update_or_create(\n            email=email,\n            username=username,\n            defaults={\n                \"first_name\": first_name,\n                \"last_name\": last_name,\n                \"password\": password_hash,\n                \"is_superuser\": True,\n                \"is_staff\": True,\n            },\n        )\n        action = \"created\" if created else \"updated\"\n        print(f\"Successfully {action} user({email=})\")\n\ncreate_initial_users(user_credentials)\n"
---
# Source: ifrcgo-risk-module-helm/charts/app/templates/api/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: risk-1-api
  labels:
    app: risk-1
    component: api
    environment: ALPHA-1
    release: release-name
spec:
  type: ClusterIP
  selector:
    app: risk-1
    component: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
# Source: ifrcgo-risk-module-helm/charts/app/templates/api/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: risk-1-api
  annotations:
    argocd.argoproj.io/sync-wave: "30"
    reloader.stakater.com/auto: "true"
  labels:
    app: risk-1
    component: api
    environment: ALPHA-1
    release: release-name
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: risk-1
      component: api
  template:
    metadata:
      annotations:
        checksum/secret: 79d2dd5323b3376b79ce3f74dfc7c574a19e883e445eda033103627ff729c9a5
        checksum/configmap: 6882edae1c39e4b22afd8da880c9b404913ad4b049d51eaa3c03a464e0d89f93
      labels:
        app: risk-1
        component: api
    spec:
      terminationGracePeriodSeconds: 38
      containers:
        - name: api
          image: "local.git.com/ifrcgo/risk:develop.xxxxxxxx"
          imagePullPolicy: IfNotPresent
          command:
            - gunicorn
            - risk_module.wsgi:application
            - --bind
            - 0.0.0.0:80
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /healthz/live/
              port: http
            periodSeconds: 20
            timeoutSeconds: 2
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /healthz/ready/
              port: http
            periodSeconds: 10
            timeoutSeconds: 2
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /healthz/ready/
              port: http
            periodSeconds: 5
          resources:
            limits:
              cpu: "4"
              memory: 2Gi
            requests:
              cpu: "0.1"
              memory: 1Gi
          envFrom:
            - secretRef:
                name: risk-1-secret
            - configMapRef:
                name: risk-1-env-name
          env:
            - name: DJANGO_APP_TYPE
              value: "web"
            
          lifecycle:
            preStop:
              sleep:
                seconds: 8

---
# Source: ifrcgo-risk-module-helm/charts/app/templates/worker-addons/deployment.yaml
# Addon: beat
apiVersion: apps/v1
kind: Deployment
metadata:
  name: risk-1-worker-beat
  annotations:
    argocd.argoproj.io/sync-wave: "30"
    reloader.stakater.com/auto: "true"
  labels:
    app: risk-1
    component: worker-addon
    addon: beat
    environment: ALPHA-1
    release: release-name
spec:
  strategy:
    type: Recreate
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: risk-1
      component: worker-addon
      addon: beat
  template:
    metadata:
      annotations:
        checksum/secret: 79d2dd5323b3376b79ce3f74dfc7c574a19e883e445eda033103627ff729c9a5
        checksum/configmap: 6882edae1c39e4b22afd8da880c9b404913ad4b049d51eaa3c03a464e0d89f93
      labels:
        app: risk-1
        component: worker-addon
        addon: beat
    spec:
      volumes:
        - emptyDir:
            medium: Memory
            sizeLimit: 1Mi
          name: celery-heartbeat
      containers:
        - name: beat
          image: "local.git.com/ifrcgo/risk:develop.xxxxxxxx"
          imagePullPolicy: IfNotPresent
          command:
            - celery
            - --app=risk_module
            - beat
            - --loglevel=info
            - --scheduler=banjo_utils.celery_health.database.HeartbeatDatabaseScheduler
          livenessProbe:
            exec:
              command:
              - banjo-celery-probe
              - --max-age
              - "360"
            failureThreshold: 3
            periodSeconds: 60
            timeoutSeconds: 5
          resources:
            limits:
              cpu: "1"
              memory: 0.5Gi
            requests:
              cpu: "0.1"
              memory: 0.2Gi
          envFrom:
            - secretRef:
                name: risk-1-secret
            - configMapRef:
                name: risk-1-env-name
          env:
            - name: DJANGO_APP_TYPE
              value: "worker"
            
            - name: BANJO_CELERY_HEARTBEAT_FILE
              value: "/var/run/celery/beat_heartbeat"
          volumeMounts:
            - mountPath: /var/run/celery
              name: celery-heartbeat

---
# Source: ifrcgo-risk-module-helm/charts/app/templates/worker/deployment.yaml
# Queue: default
apiVersion: apps/v1
kind: Deployment
metadata:
  name: risk-1-worker-default
  annotations:
    argocd.argoproj.io/sync-wave: "30"
    reloader.stakater.com/auto: "true"
  labels:
    app: risk-1
    component: worker
    queue: default
    environment: ALPHA-1
    release: release-name
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: risk-1
      component: worker
      queue: default
  template:
    metadata:
      annotations:
        checksum/secret: 79d2dd5323b3376b79ce3f74dfc7c574a19e883e445eda033103627ff729c9a5
        checksum/configmap: 6882edae1c39e4b22afd8da880c9b404913ad4b049d51eaa3c03a464e0d89f93
      labels:
        app: risk-1
        component: worker
        queue: default
    spec:
      volumes:
        - emptyDir:
            medium: Memory
            sizeLimit: 1Mi
          name: celery-heartbeat
      containers:
        - name: worker
          command:
            - celery
            - --app=risk_module
            - worker
            - --loglevel=INFO
            - --queues=celery
            - --max-tasks-per-child=20
          image: "local.git.com/ifrcgo/risk:develop.xxxxxxxx"
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
              - banjo-celery-probe
            failureThreshold: 6
            periodSeconds: 20
            timeoutSeconds: 5
          startupProbe:
            exec:
              command:
              - banjo-celery-probe
            failureThreshold: 30
            periodSeconds: 5
          resources:
            limits:
              cpu: "4"
              memory: 2Gi
            requests:
              cpu: "0.1"
              memory: 1Gi
          envFrom:
            - secretRef:
                name: risk-1-secret
            - configMapRef:
                name: risk-1-env-name
          env:
            - name: DJANGO_APP_TYPE
              value: "worker"
            
            - name: BANJO_CELERY_HEARTBEAT_FILE
              value: "/var/run/celery/worker_heartbeat"
          volumeMounts:
            - mountPath: /var/run/celery
              name: celery-heartbeat

---
# Source: ifrcgo-risk-module-helm/charts/app/templates/hooks/job.yaml
# Hook: collect-static
apiVersion: batch/v1
kind: Job
metadata:
  name: risk-1-collect-static
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "20"
  labels:
    app: risk-1
    component: hook
    hookName: collect-static
    environment: ALPHA-1
    release: release-name
spec:
  template:
    metadata:
      annotations:
        checksum/secret: 79d2dd5323b3376b79ce3f74dfc7c574a19e883e445eda033103627ff729c9a5
        checksum/configmap: 6882edae1c39e4b22afd8da880c9b404913ad4b049d51eaa3c03a464e0d89f93
      labels:
        app: risk-1
        component: hook
        hookName: collect-static
    spec:
      restartPolicy: "Never"
      containers:
        - name: collect-static
          image: "local.git.com/ifrcgo/risk:develop.xxxxxxxx"
          imagePullPolicy: IfNotPresent
          command: 
            - ./manage.py
            - collectstatic
            - --noinput
          resources:
            limits:
              cpu: "4"
              memory: 1Gi
            requests:
              cpu: "0.1"
              memory: 1Gi
          envFrom:
            - secretRef:
                name: risk-1-secret
            - configMapRef:
                name: risk-1-env-name
          env:
            - name: DJANGO_APP_TYPE
              value: "hook"
---
# Source: ifrcgo-risk-module-helm/charts/app/templates/hooks/job.yaml
# Hook: create-users
apiVersion: batch/v1
kind: Job
metadata:
  name: risk-1-create-users
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "25"
  labels:
    app: risk-1
    component: hook
    hookName: create-users
    environment: ALPHA-1
    release: release-name
spec:
  template:
    metadata:
      annotations:
        checksum/secret: 79d2dd5323b3376b79ce3f74dfc7c574a19e883e445eda033103627ff729c9a5
        checksum/configmap: 6882edae1c39e4b22afd8da880c9b404913ad4b049d51eaa3c03a464e0d89f93
      labels:
        app: risk-1
        component: hook
        hookName: create-users
    spec:
      restartPolicy: "Never"
      volumes:
        - configMap:
            name: risk-1-create-users-files
          name: hook-files
      containers:
        - name: create-users
          image: "local.git.com/ifrcgo/risk:develop.xxxxxxxx"
          imagePullPolicy: IfNotPresent
          command: 
            - sh
            - -c
            - ./manage.py shell < /etc/hook-files/create_users.py
          resources:
            limits:
              cpu: "4"
              memory: 1Gi
            requests:
              cpu: "0.1"
              memory: 1Gi
          envFrom:
            - secretRef:
                name: risk-1-secret
            - configMapRef:
                name: risk-1-env-name
          env:
            - name: DJANGO_APP_TYPE
              value: "hook"
            
            - name: ADMIN_USER_EMAIL_PASSWORD_SET
              value: "IFRC:Admin:admin@ifrc.org:password_hash"
          volumeMounts:
            - mountPath: /etc/hook-files
              name: hook-files
              readOnly: true
---
# Source: ifrcgo-risk-module-helm/charts/app/templates/hooks/job.yaml
# Hook: db-migrate
apiVersion: batch/v1
kind: Job
metadata:
  generateName: risk-1-db-migrate-
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "20"
  labels:
    app: risk-1
    component: hook
    hookName: db-migrate
    environment: ALPHA-1
    release: release-name
spec:
  activeDeadlineSeconds: 3600
  ttlSecondsAfterFinished: 604800
  template:
    metadata:
      annotations:
        checksum/secret: 79d2dd5323b3376b79ce3f74dfc7c574a19e883e445eda033103627ff729c9a5
        checksum/configmap: 6882edae1c39e4b22afd8da880c9b404913ad4b049d51eaa3c03a464e0d89f93
      labels:
        app: risk-1
        component: hook
        hookName: db-migrate
    spec:
      restartPolicy: "Never"
      containers:
        - name: db-migrate
          image: "local.git.com/ifrcgo/risk:develop.xxxxxxxx"
          imagePullPolicy: IfNotPresent
          command: 
            - ./manage.py
            - migrate
          resources:
            limits:
              cpu: "4"
              memory: 1Gi
            requests:
              cpu: "0.1"
              memory: 1Gi
          envFrom:
            - secretRef:
                name: risk-1-secret
            - configMapRef:
                name: risk-1-env-name
          env:
            - name: DJANGO_APP_TYPE
              value: "hook"
---
# Source: ifrcgo-risk-module-helm/charts/app/templates/hooks/job.yaml
# Hook: wait-for-resources
apiVersion: batch/v1
kind: Job
metadata:
  name: risk-1-wait-for-resources
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "10"
  labels:
    app: risk-1
    component: hook
    hookName: wait-for-resources
    environment: ALPHA-1
    release: release-name
spec:
  template:
    metadata:
      annotations:
        checksum/secret: 79d2dd5323b3376b79ce3f74dfc7c574a19e883e445eda033103627ff729c9a5
        checksum/configmap: 6882edae1c39e4b22afd8da880c9b404913ad4b049d51eaa3c03a464e0d89f93
      labels:
        app: risk-1
        component: hook
        hookName: wait-for-resources
    spec:
      restartPolicy: "Never"
      containers:
        - name: wait-for-resources
          image: "local.git.com/ifrcgo/risk:develop.xxxxxxxx"
          imagePullPolicy: IfNotPresent
          command: 
            - ./manage.py
            - wait_for_resources
            - --db
            - --cache
            - --minio
          resources:
            limits:
              cpu: "4"
              memory: 1Gi
            requests:
              cpu: "0.1"
              memory: 1Gi
          envFrom:
            - secretRef:
                name: risk-1-secret
            - configMapRef:
                name: risk-1-env-name
          env:
            - name: DJANGO_APP_TYPE
              value: "hook"
            

---
# Source: ifrcgo-risk-module-helm/charts/app/templates/api/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: risk-1-api
  labels:
    app: risk-1
    component: api
    environment: ALPHA-1
    release: release-name
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  rules:
    - host: "risk-1.ifrcgo.local.example.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: risk-1-api
                port:
                  number: 80

---
# Source: ifrcgo-risk-module-helm/charts/app/templates/extraManifests.yaml
# Manifest: dragonflydb-cluster
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  labels:
    app.kubernetes.io/name: dragonfly
  name: risk-module-dragonfly
spec:
  args:
  - --dbfilename=mainSnapshot
  replicas: 1
  resources:
    limits:
      cpu: "1"
      memory: 750Mi
    requests:
      cpu: "0.1"
      memory: 500Mi
  snapshot:
    cron: '*/5 * * * *'
    persistentVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: local-path
