apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    service: {{ include "application.fullname" . }}-api
  name: {{ include "application.fullname" .}}-api
spec:
  selector:
    matchLabels:
      service: {{ include "application.fullname" . }}-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ include "application.fullname" . }}-api
        service: {{ include "application.fullname" . }}-api
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          name: {{ include "application.fullname" . }}-api
          args:
            - bash
            - -c
            - /code/scripts/run_develop.sh
          envFrom:
            - configMapRef:
                name: {{ include "application.fullname" . }}-app-config
            - secretRef:
                name: {{ include "application.secretname" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9001
              protocol: TCP
          volumeMounts:
            - name: {{ include "application.secretname" . }}
              mountPath: /mnt/secrets-store
              readOnly: true
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      serviceAccountName: {{ include "application.serviceAccountName" . }}
      volumes:
        - name: {{ include "application.secretname" . }}
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "application.fullname" . }}-secret-provider