apiVersion: v1
kind: Service
metadata:
  name: {{ include "application.fullname" .}}-api
  labels:
    app: {{ include "application.fullname" . }}-api
spec:
  type: ClusterIP
  selector:
    service: {{ include "application.fullname" . }}-api
  ports:
    - protocol: TCP
      port: 80       
      targetPort: 9001