# Generated by Django 3.2.7 on 2021-10-23 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oddrin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('hazard_title', models.CharField(max_length=255, verbose_name='hazard title')),
                ('hazard_type', models.CharField(blank=True, choices=[('earthquake', 'Earthquake'), ('flood', 'Flood'), ('cyclone', 'Cyclone'), ('epidemic', 'Epidemic'), ('food_insecurity', 'Food Insecurity'), ('storm_surge', 'Storm Surge')], max_length=100, verbose_name='hazard type')),
                ('glide_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='glide number')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='longitude')),
                ('iso3', models.CharField(blank=True, max_length=3, null=True, verbose_name='iso3')),
                ('people_exposed', models.IntegerField(blank=True, null=True, verbose_name='people exposed')),
                ('people_displaced', models.IntegerField(blank=True, null=True, verbose_name='people displaced')),
                ('buildings_exposed', models.IntegerField(blank=True, null=True, verbose_name='buildings exposed')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oddrin_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oddrin_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
