# Generated by Django 3.2.8 on 2021-10-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddrin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idmc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255, verbose_name='country')),
                ('iso3', models.CharField(blank=True, max_length=3, null=True, verbose_name='iso3')),
                ('hazard_type', models.CharField(blank=True, choices=[('flood', 'Flood'), ('storm', 'Storm')], max_length=100, verbose_name='hazard type')),
                ('confidence_type', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('undefined', 'Undefined')], max_length=100, verbose_name='confidence type')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('annual_average_displacement', models.FloatField(blank=True, null=True, verbose_name='annual average displacement')),
                ('january', models.FloatField(blank=True, null=True, verbose_name='january')),
                ('february', models.FloatField(blank=True, null=True, verbose_name='february')),
                ('march', models.FloatField(blank=True, null=True, verbose_name='march')),
                ('april', models.FloatField(blank=True, null=True, verbose_name='april')),
                ('may', models.FloatField(blank=True, null=True, verbose_name='may')),
                ('june', models.FloatField(blank=True, null=True, verbose_name='june')),
                ('july', models.FloatField(blank=True, null=True, verbose_name='july')),
                ('august', models.FloatField(blank=True, null=True, verbose_name='august')),
                ('september', models.FloatField(blank=True, null=True, verbose_name='september')),
                ('october', models.FloatField(blank=True, null=True, verbose_name='october')),
                ('november', models.FloatField(blank=True, null=True, verbose_name='november')),
                ('december', models.FloatField(blank=True, null=True, verbose_name='december')),
            ],
        ),
    ]
