# Generated by Django 3.2.8 on 2021-10-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddrin', '0002_idmc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idmc',
            name='hazard_type',
            field=models.CharField(blank=True, choices=[('flood', 'Flood'), ('storm', 'Storm'), ('food_insecurity', 'Food Insecurity')], max_length=100, verbose_name='hazard type'),
        ),
    ]
