# Generated by Django 3.2.8 on 2021-10-28 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0003_auto_20211028_0451'),
        ('oddrin', '0003_alter_idmc_hazard_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='oddrin',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='oddrin/', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='oddrin',
            name='hazard_type',
            field=models.CharField(blank=True, choices=[('earthquake', 'Earthquake'), ('flood', 'Flood'), ('cyclone', 'Cyclone'), ('epidemic', 'Epidemic'), ('food_insecurity', 'Food Insecurity'), ('storm', 'Storm'), ('drought', 'Drought'), ('tsunami', 'Tsunami')], max_length=100, verbose_name='hazard type'),
        ),
        migrations.CreateModel(
            name='InformRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard_type', models.CharField(blank=True, choices=[('earthquake', 'Earthquake'), ('flood', 'Flood'), ('cyclone', 'Cyclone'), ('epidemic', 'Epidemic'), ('food_insecurity', 'Food Insecurity'), ('storm', 'Storm'), ('drought', 'Drought'), ('tsunami', 'Tsunami')], max_length=100, verbose_name='hazard type')),
                ('risk_score', models.FloatField(blank=True, null=True, verbose_name='risk_score')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipc.country', verbose_name='country')),
            ],
        ),
    ]
