# Generated by Django 3.2.8 on 2021-11-01 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0003_auto_20211028_0451'),
        ('oddrin', '0004_auto_20211028_0451'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdmcSuddenOnset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard_type', models.CharField(blank=True, choices=[('earthquake', 'Earthquake'), ('flood', 'Flood'), ('cyclone', 'Cyclone'), ('epidemic', 'Epidemic'), ('food_insecurity', 'Food Insecurity'), ('storm', 'Storm'), ('drought', 'Drought'), ('tsunami', 'Tsunami')], max_length=100, verbose_name='hazard type')),
                ('annual_average_displacement', models.IntegerField(blank=True, null=True, verbose_name='annual average displacement')),
                ('return_period_20_years', models.IntegerField(blank=True, null=True, verbose_name='return period 20 years')),
                ('return_period_50_years', models.IntegerField(blank=True, null=True, verbose_name='return period 50 years')),
                ('return_period_100_years', models.IntegerField(blank=True, null=True, verbose_name='return period 100 years')),
                ('return_period_250_years', models.IntegerField(blank=True, null=True, verbose_name='return period 250 years')),
                ('return_period_1000_years', models.IntegerField(blank=True, null=True, verbose_name='return period 1000 years')),
                ('return_period_1500_years', models.IntegerField(blank=True, null=True, verbose_name='return period 1500 years')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipc.country', verbose_name='country')),
            ],
        ),
    ]
