# Generated by Django 3.2.8 on 2021-11-01 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0003_auto_20211028_0451'),
        ('oddrin', '0005_idmcsuddenonset'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformRiskSeasonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard_type', models.CharField(blank=True, choices=[('earthquake', 'Earthquake'), ('flood', 'Flood'), ('cyclone', 'Cyclone'), ('epidemic', 'Epidemic'), ('food_insecurity', 'Food Insecurity'), ('storm', 'Storm'), ('drought', 'Drought'), ('tsunami', 'Tsunami')], max_length=100, verbose_name='hazard type')),
                ('january', models.FloatField(blank=True, null=True, verbose_name='january')),
                ('february', models.FloatField(blank=True, null=True, verbose_name='february')),
                ('march', models.FloatField(blank=True, null=True, verbose_name='march')),
                ('april', models.FloatField(blank=True, null=True, verbose_name='april')),
                ('may', models.FloatField(blank=True, null=True, verbose_name='may')),
                ('june', models.FloatField(blank=True, null=True, verbose_name='june')),
                ('july', models.FloatField(blank=True, null=True, verbose_name='july')),
                ('august', models.FloatField(blank=True, null=True, verbose_name='august')),
                ('september', models.FloatField(blank=True, null=True, verbose_name='september')),
                ('october', models.FloatField(blank=True, null=True, verbose_name='october')),
                ('november', models.FloatField(blank=True, null=True, verbose_name='november')),
                ('december', models.FloatField(blank=True, null=True, verbose_name='december')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipc.country', verbose_name='country')),
            ],
        ),
    ]
