# Generated by Django 3.2.8 on 2021-11-08 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oddrin', '0006_informriskseasonal'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to='oddrin/', verbose_name='file')),
            ],
        ),
        migrations.AlterField(
            model_name='oddrin',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oddrin.riskfile', verbose_name='file'),
        ),
    ]
