# Generated by Django 3.2.8 on 2021-11-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddrin', '0007_auto_20211108_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='oddrin',
            name='higher_displacement',
            field=models.IntegerField(blank=True, null=True, verbose_name='higher displacement'),
        ),
        migrations.AddField(
            model_name='oddrin',
            name='lower_displacement',
            field=models.IntegerField(blank=True, null=True, verbose_name='lower displacement'),
        ),
        migrations.AlterField(
            model_name='idmc',
            name='hazard_type',
            field=models.CharField(blank=True, choices=[('EQ', 'Earthquake'), ('FL', 'Flood'), ('TC', 'Cyclone'), ('EP', 'Epidemic'), ('FI', 'Food Insecurity'), ('SS', 'Storm'), ('DR', 'Drought'), ('TS', 'Tsunami')], max_length=100, verbose_name='hazard type'),
        ),
        migrations.AlterField(
            model_name='idmcsuddenonset',
            name='hazard_type',
            field=models.CharField(blank=True, choices=[('EQ', 'Earthquake'), ('FL', 'Flood'), ('TC', 'Cyclone'), ('EP', 'Epidemic'), ('FI', 'Food Insecurity'), ('SS', 'Storm'), ('DR', 'Drought'), ('TS', 'Tsunami')], max_length=100, verbose_name='hazard type'),
        ),
        migrations.AlterField(
            model_name='informrisk',
            name='hazard_type',
            field=models.CharField(blank=True, choices=[('EQ', 'Earthquake'), ('FL', 'Flood'), ('TC', 'Cyclone'), ('EP', 'Epidemic'), ('FI', 'Food Insecurity'), ('SS', 'Storm'), ('DR', 'Drought'), ('TS', 'Tsunami')], max_length=100, verbose_name='hazard type'),
        ),
        migrations.AlterField(
            model_name='informriskseasonal',
            name='hazard_type',
            field=models.CharField(blank=True, choices=[('EQ', 'Earthquake'), ('FL', 'Flood'), ('TC', 'Cyclone'), ('EP', 'Epidemic'), ('FI', 'Food Insecurity'), ('SS', 'Storm'), ('DR', 'Drought'), ('TS', 'Tsunami')], max_length=100, verbose_name='hazard type'),
        ),
        migrations.AlterField(
            model_name='oddrin',
            name='hazard_type',
            field=models.CharField(blank=True, choices=[('EQ', 'Earthquake'), ('FL', 'Flood'), ('TC', 'Cyclone'), ('EP', 'Epidemic'), ('FI', 'Food Insecurity'), ('SS', 'Storm'), ('DR', 'Drought'), ('TS', 'Tsunami')], max_length=100, verbose_name='hazard type'),
        ),
    ]
