# Generated by Django 3.2.8 on 2021-11-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddrin', '0008_auto_20211111_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idmc',
            name='hazard_type',
            field=models.CharField(blank=True, choices=[('EQ', 'Earthquake'), ('FL', 'Flood'), ('TC', 'Cyclone'), ('EP', 'Epidemic'), ('FI', 'Food Insecurity'), ('SS', 'Storm'), ('DR', 'Drought'), ('TS', 'Tsunami')], max_length=100, null=True, verbose_name='hazard type'),
        ),
    ]
