# Generated by Django 3.2.9 on 2021-11-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddrin', '0009_alter_idmc_hazard_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='oddrin',
            name='processed_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='processed file'),
        ),
        migrations.AlterField(
            model_name='oddrin',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='file'),
        ),
    ]
