# Generated by Django 3.2.9 on 2021-11-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddrin', '0010_auto_20211117_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oddrin',
            name='processed_file',
        ),
        migrations.AddField(
            model_name='oddrin',
            name='file_type',
            field=models.CharField(blank=True, choices=[('raster', 'Raster'), ('vector', 'Vector')], max_length=100, verbose_name='file type'),
        ),
        migrations.AddField(
            model_name='oddrin',
            name='mapbox_layer_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='mapbox id'),
        ),
    ]
