# Generated by Django 3.2.8 on 2021-11-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddrin', '0011_auto_20211124_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='oddrin',
            name='source_type',
            field=models.CharField(blank=True, choices=[('ODD', 'Oddrin'), ('PDC', 'Pdc')], max_length=100, verbose_name='source type'),
        ),
        migrations.AddField(
            model_name='oddrin',
            name='uuid',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='uuid'),
        ),
    ]
