# Generated by Django 3.2.8 on 2021-11-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddrin', '0012_auto_20211130_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oddrin',
            name='source_type',
            field=models.CharField(blank=True, choices=[('oddrin', 'Oddrin'), ('pdc', 'Pdc')], max_length=100, verbose_name='source type'),
        ),
    ]
