# Generated by Django 3.2.8 on 2021-12-07 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0009_auto_20211130_0901'),
        ('oddrin', '0013_alter_oddrin_source_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplacementData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso3', models.CharField(blank=True, max_length=3, null=True, verbose_name='iso3')),
                ('hazard_type', models.CharField(blank=True, choices=[('EQ', 'Earthquake'), ('FL', 'Flood'), ('TC', 'Cyclone'), ('EP', 'Epidemic'), ('FI', 'Food Insecurity'), ('SS', 'Storm'), ('DR', 'Drought'), ('TS', 'Tsunami')], max_length=100, null=True, verbose_name='hazard type')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('annual_average_displacement', models.FloatField(blank=True, null=True, verbose_name='annual average displacement')),
                ('january', models.FloatField(blank=True, null=True, verbose_name='january')),
                ('february', models.FloatField(blank=True, null=True, verbose_name='february')),
                ('march', models.FloatField(blank=True, null=True, verbose_name='march')),
                ('april', models.FloatField(blank=True, null=True, verbose_name='april')),
                ('may', models.FloatField(blank=True, null=True, verbose_name='may')),
                ('june', models.FloatField(blank=True, null=True, verbose_name='june')),
                ('july', models.FloatField(blank=True, null=True, verbose_name='july')),
                ('august', models.FloatField(blank=True, null=True, verbose_name='august')),
                ('september', models.FloatField(blank=True, null=True, verbose_name='september')),
                ('october', models.FloatField(blank=True, null=True, verbose_name='october')),
                ('november', models.FloatField(blank=True, null=True, verbose_name='november')),
                ('december', models.FloatField(blank=True, null=True, verbose_name='december')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipc.country')),
            ],
        ),
    ]
