# Generated by Django 3.2.8 on 2021-12-09 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0011_auto_20211209_1003'),
        ('oddrin', '0014_displacementdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displacementdata',
            name='hazard_type',
            field=models.CharField(blank=True, choices=[('EQ', 'Earthquake'), ('FL', 'Flood'), ('TC', 'Cyclone'), ('EP', 'Epidemic'), ('FI', 'Food Insecurity'), ('SS', 'Storm Surge'), ('DR', 'Drought'), ('TS', 'Tsunami'), ('CD', 'Cyclonic Wind')], max_length=100, null=True, verbose_name='hazard type'),
        ),
        migrations.AlterField(
            model_name='idmc',
            name='hazard_type',
            field=models.CharField(blank=True, choices=[('EQ', 'Earthquake'), ('FL', 'Flood'), ('TC', 'Cyclone'), ('EP', 'Epidemic'), ('FI', 'Food Insecurity'), ('SS', 'Storm Surge'), ('DR', 'Drought'), ('TS', 'Tsunami'), ('CD', 'Cyclonic Wind')], max_length=100, null=True, verbose_name='hazard type'),
        ),
        migrations.AlterField(
            model_name='idmcsuddenonset',
            name='hazard_type',
            field=models.CharField(blank=True, choices=[('EQ', 'Earthquake'), ('FL', 'Flood'), ('TC', 'Cyclone'), ('EP', 'Epidemic'), ('FI', 'Food Insecurity'), ('SS', 'Storm Surge'), ('DR', 'Drought'), ('TS', 'Tsunami'), ('CD', 'Cyclonic Wind')], max_length=100, verbose_name='hazard type'),
        ),
        migrations.AlterField(
            model_name='informrisk',
            name='hazard_type',
            field=models.CharField(blank=True, choices=[('EQ', 'Earthquake'), ('FL', 'Flood'), ('TC', 'Cyclone'), ('EP', 'Epidemic'), ('FI', 'Food Insecurity'), ('SS', 'Storm Surge'), ('DR', 'Drought'), ('TS', 'Tsunami'), ('CD', 'Cyclonic Wind')], max_length=100, verbose_name='hazard type'),
        ),
        migrations.AlterField(
            model_name='informriskseasonal',
            name='hazard_type',
            field=models.CharField(blank=True, choices=[('EQ', 'Earthquake'), ('FL', 'Flood'), ('TC', 'Cyclone'), ('EP', 'Epidemic'), ('FI', 'Food Insecurity'), ('SS', 'Storm Surge'), ('DR', 'Drought'), ('TS', 'Tsunami'), ('CD', 'Cyclonic Wind')], max_length=100, verbose_name='hazard type'),
        ),
        migrations.AlterField(
            model_name='oddrin',
            name='hazard_type',
            field=models.CharField(blank=True, choices=[('EQ', 'Earthquake'), ('FL', 'Flood'), ('TC', 'Cyclone'), ('EP', 'Epidemic'), ('FI', 'Food Insecurity'), ('SS', 'Storm Surge'), ('DR', 'Drought'), ('TS', 'Tsunami'), ('CD', 'Cyclonic Wind')], max_length=100, verbose_name='hazard type'),
        ),
        migrations.CreateModel(
            name='GarHazard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard_type', models.CharField(blank=True, choices=[('EQ', 'Earthquake'), ('FL', 'Flood'), ('TC', 'Cyclone'), ('EP', 'Epidemic'), ('FI', 'Food Insecurity'), ('SS', 'Storm Surge'), ('DR', 'Drought'), ('TS', 'Tsunami'), ('CD', 'Cyclonic Wind')], max_length=100, verbose_name='hazard type')),
                ('return_period_20_years', models.FloatField(blank=True, null=True, verbose_name='return period 20 years')),
                ('return_period_50_years', models.FloatField(blank=True, null=True, verbose_name='return period 50 years')),
                ('return_period_100_years', models.FloatField(blank=True, null=True, verbose_name='return period 100 years')),
                ('return_period_250_years', models.FloatField(blank=True, null=True, verbose_name='return period 250 years')),
                ('return_period_500_years', models.FloatField(blank=True, null=True, verbose_name='return period 500 years')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipc.country', verbose_name='country')),
            ],
        ),
    ]
