# Generated by Django 3.2.8 on 2022-01-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddrin', '0016_pdc_pdcdisplacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='oddrin',
            name='cog_file',
            field=models.FileField(blank=True, null=True, upload_to='oddrin/cog_files', verbose_name='cog file'),
        ),
        migrations.AlterField(
            model_name='oddrin',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='oddrin/files', verbose_name='file'),
        ),
    ]
