# Generated by Django 3.2.8 on 2022-01-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddrin', '0016_pdc_pdcdisplacement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oddrin',
            name='mapbox_layer_id',
        ),
        migrations.AlterField(
            model_name='oddrin',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='oddrin/files/', verbose_name='file'),
        ),
    ]
