# Generated by Django 3.2.8 on 2022-01-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddrin', '0017_auto_20220105_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdc',
            name='features',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='features'),
        ),
    ]
