# Generated by Django 3.2.8 on 2022-01-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddrin', '0017_auto_20220105_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='oddrin',
            name='cog_file',
            field=models.FileField(blank=True, null=True, upload_to='oddrin/cog_files/', verbose_name='cog file'),
        ),
    ]
