# Generated by Django 3.2.11 on 2022-01-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddrin', '0018_pdc_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='garhazard',
            name='return_period_25_years',
            field=models.FloatField(blank=True, null=True, verbose_name='return period 25 years'),
        ),
    ]
