# Generated by Django 3.2.8 on 2021-10-26 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('iso3', models.CharField(blank=True, max_length=3, null=True, verbose_name='iso3')),
                ('iso', models.CharField(blank=True, max_length=2, null=True, verbose_name='iso3')),
            ],
        ),
        migrations.CreateModel(
            name='Ipc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('analysis_date', models.DateField(blank=True, null=True, verbose_name='analysis date')),
                ('phase_population', models.IntegerField(verbose_name='phase population')),
                ('census_population', models.IntegerField(verbose_name='census population')),
                ('current_from_date', models.DateField(blank=True, null=True, verbose_name='current from date')),
                ('current_to_date', models.DateField(blank=True, null=True, verbose_name='current to date')),
                ('projected_from_date', models.DateField(blank=True, null=True, verbose_name='projected from date')),
                ('projected_to_date', models.DateField(blank=True, null=True, verbose_name='projected to date')),
                ('hazard_type', models.CharField(blank=True, choices=[('earthquake', 'Earthquake'), ('flood', 'Flood'), ('cyclone', 'Cyclone'), ('epidemic', 'Epidemic'), ('food_insecurity', 'Food Insecurity'), ('storm_surge', 'Storm Surge')], max_length=100, verbose_name='hazard type')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipc.country', verbose_name='country')),
            ],
        ),
    ]
