# Generated by Django 3.2.8 on 2021-10-26 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalDisplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard_type', models.CharField(blank=True, choices=[('earthquake', 'Earthquake'), ('flood', 'Flood'), ('cyclone', 'Cyclone'), ('epidemic', 'Epidemic'), ('food_insecurity', 'Food Insecurity'), ('storm_surge', 'Storm Surge')], max_length=100, verbose_name='hazard type')),
                ('total_displacement', models.IntegerField(blank=True, null=True, verbose_name='total displacement')),
                ('year', models.IntegerField(verbose_name='year')),
                ('month', models.IntegerField(verbose_name='month')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipc.country', verbose_name='country')),
            ],
        ),
    ]
