# Generated by Django 3.2.8 on 2021-10-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0002_globaldisplacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globaldisplacement',
            name='hazard_type',
            field=models.CharField(blank=True, choices=[('earthquake', 'Earthquake'), ('flood', 'Flood'), ('cyclone', 'Cyclone'), ('epidemic', 'Epidemic'), ('food_insecurity', 'Food Insecurity'), ('storm', 'Storm'), ('drought', 'Drought'), ('tsunami', 'Tsunami')], max_length=100, verbose_name='hazard type'),
        ),
        migrations.AlterField(
            model_name='ipc',
            name='hazard_type',
            field=models.CharField(blank=True, choices=[('earthquake', 'Earthquake'), ('flood', 'Flood'), ('cyclone', 'Cyclone'), ('epidemic', 'Epidemic'), ('food_insecurity', 'Food Insecurity'), ('storm', 'Storm'), ('drought', 'Drought'), ('tsunami', 'Tsunami')], max_length=100, verbose_name='hazard type'),
        ),
    ]
