# Generated by Django 3.2.8 on 2021-11-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0003_auto_20211028_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipc',
            name='current_from_date',
        ),
        migrations.RemoveField(
            model_name='ipc',
            name='current_to_date',
        ),
        migrations.RemoveField(
            model_name='ipc',
            name='projected_from_date',
        ),
        migrations.RemoveField(
            model_name='ipc',
            name='projected_to_date',
        ),
        migrations.AddField(
            model_name='ipc',
            name='analysis_period_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='analysis period end date'),
        ),
        migrations.AddField(
            model_name='ipc',
            name='analysis_period_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='analysis period start date'),
        ),
        migrations.AddField(
            model_name='ipc',
            name='is_projected',
            field=models.BooleanField(default=False, verbose_name='is projected'),
        ),
    ]
