# Generated by Django 3.2.8 on 2021-11-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0004_auto_20211102_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globaldisplacement',
            name='hazard_type',
            field=models.CharField(blank=True, choices=[('EQ', 'Earthquake'), ('FL', 'Flood'), ('TC', 'Cyclone'), ('EP', 'Epidemic'), ('FI', 'Food Insecurity'), ('SS', 'Storm'), ('DR', 'Drought'), ('TS', 'Tsunami')], max_length=100, verbose_name='hazard type'),
        ),
        migrations.AlterField(
            model_name='ipc',
            name='hazard_type',
            field=models.CharField(blank=True, choices=[('EQ', 'Earthquake'), ('FL', 'Flood'), ('TC', 'Cyclone'), ('EP', 'Epidemic'), ('FI', 'Food Insecurity'), ('SS', 'Storm'), ('DR', 'Drought'), ('TS', 'Tsunami')], max_length=100, verbose_name='hazard type'),
        ),
    ]
