# Generated by Django 3.2.9 on 2021-11-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0005_auto_20211111_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipc',
            name='analysis_period_end_date',
        ),
        migrations.RemoveField(
            model_name='ipc',
            name='analysis_period_start_date',
        ),
        migrations.AddField(
            model_name='ipc',
            name='current_period_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='current period end date'),
        ),
        migrations.AddField(
            model_name='ipc',
            name='current_period_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='current period start date'),
        ),
        migrations.AddField(
            model_name='ipc',
            name='projected_period_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='projected period end date'),
        ),
        migrations.AddField(
            model_name='ipc',
            name='projected_period_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='projected period start date'),
        ),
        migrations.AddField(
            model_name='ipc',
            name='projected_phase_population',
            field=models.IntegerField(null=True, verbose_name='projected phase population'),
        ),
    ]
