# Generated by Django 3.2.9 on 2021-11-26 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0006_auto_20211125_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpcMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateField(blank=True, null=True, verbose_name='analysis date')),
                ('phase_population', models.IntegerField(null=True, verbose_name='phase population')),
                ('projected_phase_population', models.IntegerField(null=True, verbose_name='projected phase population')),
                ('census_population', models.IntegerField(verbose_name='census population')),
                ('hazard_type', models.CharField(blank=True, choices=[('EQ', 'Earthquake'), ('FL', 'Flood'), ('TC', 'Cyclone'), ('EP', 'Epidemic'), ('FI', 'Food Insecurity'), ('SS', 'Storm'), ('DR', 'Drought'), ('TS', 'Tsunami')], max_length=100, verbose_name='hazard type')),
                ('is_projected', models.BooleanField(verbose_name='is projected')),
                ('year', models.IntegerField(verbose_name='year')),
                ('month', models.IntegerField(verbose_name='month')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipc.country', verbose_name='country')),
            ],
        ),
    ]
