# Generated by Django 3.2.8 on 2021-11-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0007_ipcmonthly'),
    ]

    operations = [
        migrations.AddField(
            model_name='globaldisplacement',
            name='analysis_date',
            field=models.DateField(blank=True, null=True, verbose_name='analysis date'),
        ),
        migrations.AddField(
            model_name='globaldisplacement',
            name='is_projected',
            field=models.BooleanField(null=True, verbose_name='is projected'),
        ),
    ]
