# Generated by Django 3.2.8 on 2021-12-08 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0009_auto_20211130_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThinkHazardCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.CharField(max_length=255, verbose_name='country')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('iso3', models.CharField(blank=True, max_length=3, null=True, verbose_name='iso3')),
            ],
        ),
        migrations.CreateModel(
            name='ThinkHazardInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard_level', models.CharField(choices=[('low', 'Low'), ('very low', 'Very Low'), ('medium', 'Medium'), ('high', 'High')], max_length=100, verbose_name='hazard level')),
                ('information', models.TextField(verbose_name='information')),
                ('hazard_type', models.CharField(blank=True, choices=[('EQ', 'Earthquake'), ('FL', 'Flood'), ('TC', 'Cyclone'), ('EP', 'Epidemic'), ('FI', 'Food Insecurity'), ('SS', 'Storm'), ('DR', 'Drought'), ('TS', 'Tsunami')], max_length=100, verbose_name='hazard type')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipc.country')),
            ],
        ),
    ]
