{{- if .Values.api.enabled -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ template "ifrcgo-risk-module.fullname" . }}-api-svc
  labels:
    app: {{ template "ifrcgo-risk-module.name" . }}
    component: api-service
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "ifrcgo-risk-module.name" . }}
    release: {{ .Release.Name }}
    run: {{ .Release.Name }}-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.api.containerPort }}
      nodePort: null

{{- end }}
