{{- if .Values.api.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app.kubernetes.io/name: {{ include "ifrcgo-risk-module.fullname" . }}
    app.kubernetes.io/component: {{ include "ifrcgo-risk-module.fullname" . }}-api
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
  name: {{ include "ifrcgo-risk-module.fullname" .}}-api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ifrcgo-risk-module.fullname" . }}
      app.kubernetes.io/component: {{ include "ifrcgo-risk-module.fullname" . }}-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ifrcgo-risk-module.fullname" . }}
        app.kubernetes.io/component: {{ include "ifrcgo-risk-module.fullname" . }}-api
    spec:
      containers:
        - name: {{ include "ifrcgo-risk-module.fullname" . }}-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          args:
            - bash
            - -c
            - /code/scripts/run_prod.sh
          envFrom:
            - configMapRef:
                name: {{ include "ifrcgo-risk-module.fullname" . }}-api-configmap
            - secretRef:
                name: {{ include "ifrcgo-risk-module.secretname" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.api.containerPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "ifrcgo-risk-module.secretname" . }}
              mountPath: /mnt/secrets-store
              readOnly: true
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      serviceAccountName: {{ include "ifrcgo-risk-module.serviceAccountName" . }}
      {{- if .Values.azure.aksSecretsProviderAvailable }}
      volumes:
        - name: {{ include "ifrcgo-risk-module.secretname" . }}
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "ifrcgo-risk-module.fullname" . }}-secret-provider
      {{- end }}
{{- end }}