# Generated by Django 3.2.11 on 2022-01-28 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oddrin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('hazard_title', models.CharField(max_length=255, verbose_name='hazard title')),
                ('hazard_type', models.CharField(blank=True, choices=[('EQ', 'Earthquake'), ('FL', 'Flood'), ('TC', 'Cyclone'), ('EP', 'Epidemic'), ('FI', 'Food Insecurity'), ('SS', 'Storm Surge'), ('DR', 'Drought'), ('TS', 'Tsunami'), ('CD', 'Cyclonic Wind')], max_length=100, verbose_name='hazard type')),
                ('source_type', models.CharField(blank=True, choices=[('oddrin', 'Oddrin'), ('pdc', 'Pdc')], max_length=100, verbose_name='source type')),
                ('glide_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='glide number')),
                ('uuid', models.CharField(blank=True, max_length=128, null=True, verbose_name='uuid')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='longitude')),
                ('iso3', models.CharField(blank=True, max_length=3, null=True, verbose_name='iso3')),
                ('people_exposed', models.IntegerField(blank=True, null=True, verbose_name='people exposed')),
                ('people_displaced', models.IntegerField(blank=True, null=True, verbose_name='people displaced')),
                ('buildings_exposed', models.IntegerField(blank=True, null=True, verbose_name='buildings exposed')),
                ('lower_displacement', models.IntegerField(blank=True, null=True, verbose_name='lower displacement')),
                ('higher_displacement', models.IntegerField(blank=True, null=True, verbose_name='higher displacement')),
                ('file', models.FileField(blank=True, null=True, upload_to='oddrin/files', verbose_name='file')),
                ('cog_file', models.FileField(blank=True, null=True, upload_to='oddrin/cog_files', verbose_name='cog file')),
                ('file_type', models.CharField(blank=True, choices=[('raster', 'Raster'), ('vector', 'Vector')], max_length=100, verbose_name='file type')),
            ],
        ),
        migrations.CreateModel(
            name='Pdc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hazard_id', models.CharField(max_length=255, verbose_name='hazard id')),
                ('hazard_name', models.CharField(max_length=255, verbose_name='hazard name')),
                ('hazard_type', models.CharField(blank=True, choices=[('EQ', 'Earthquake'), ('FL', 'Flood'), ('TC', 'Cyclone'), ('EP', 'Epidemic'), ('FI', 'Food Insecurity'), ('SS', 'Storm Surge'), ('DR', 'Drought'), ('TS', 'Tsunami'), ('CD', 'Cyclonic Wind')], max_length=100, verbose_name='hazard type')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('status', models.CharField(blank=True, choices=[('A', 'Active'), ('E', 'Expired')], max_length=20, verbose_name='status')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='longitude')),
                ('uuid', models.UUIDField(blank=True, null=True, verbose_name='uuid')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end_date')),
                ('features', models.JSONField(blank=True, default=None, null=True, verbose_name='features')),
            ],
        ),
        migrations.CreateModel(
            name='PdcDisplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard_type', models.CharField(blank=True, choices=[('EQ', 'Earthquake'), ('FL', 'Flood'), ('TC', 'Cyclone'), ('EP', 'Epidemic'), ('FI', 'Food Insecurity'), ('SS', 'Storm Surge'), ('DR', 'Drought'), ('TS', 'Tsunami'), ('CD', 'Cyclonic Wind')], max_length=100, verbose_name='hazard type')),
                ('population_exposure', models.JSONField(blank=True, default=None, null=True, verbose_name='population exposure')),
                ('capital_exposure', models.JSONField(blank=True, default=None, null=True, verbose_name='capital exposure')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.country', verbose_name='country')),
                ('pdc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imminent.pdc', verbose_name='pdc')),
            ],
        ),
    ]
