# Generated by Django 3.2.11 on 2022-01-28 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("imminent", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Earthquake",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_id", models.CharField(max_length=100, verbose_name="event id")),
                ("event_title", models.CharField(max_length=255, verbose_name="event title")),
                ("event_place", models.CharField(blank=True, max_length=255, null=True, verbose_name="event place")),
                ("event_date", models.DateTimeField(blank=True, null=True, verbose_name="event date")),
                ("updated_at", models.DateTimeField(blank=True, null=True, verbose_name="updated at")),
                ("latitude", models.FloatField(verbose_name="latitude")),
                ("longitude", models.FloatField(verbose_name="longitude")),
                ("depth", models.FloatField(verbose_name="depth")),
                ("magnitude", models.FloatField(verbose_name="magnitude")),
                (
                    "magnitude_type",
                    models.CharField(
                        choices=[
                            ("2", "2"),
                            ("4", "4"),
                            ("fa", "fa"),
                            ("H", "H"),
                            ("lg", "lg"),
                            ("m", "m"),
                            ("ma", "ma"),
                            ("mb", "mb"),
                            ("MbLg", "MbLg"),
                            ("Mb_lg", "Mb_lg"),
                            ("mc", "mc"),
                            ("md", "md"),
                            ("mdl", "mdl"),
                            ("Me", "Me"),
                            ("mfa", "mfa"),
                            ("mh", "mh"),
                            ("Mi", "Mi"),
                            ("mint", "mint"),
                            ("ml", "ml"),
                            ("mlg", "mlg"),
                            ("mlr", "mlr"),
                            ("mlv", "mlv"),
                            ("Ms", "Ms"),
                            ("ms_20", "ms_20"),
                            ("Mt", "Mt"),
                            ("mun", "mun"),
                            ("mw", "mw"),
                            ("mwb", "mwb"),
                            ("mwc", "mwc"),
                            ("mwp", "mwp"),
                            ("mwr", "mwr"),
                            ("mwm", "mwm"),
                            ("no", "no"),
                            ("uk", "uk"),
                            ("Unknown", "Unknown"),
                        ],
                        max_length=20,
                        verbose_name="magnitude type",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="common.country",
                        verbose_name="country",
                    ),
                ),
            ],
        ),
    ]
