# Generated by Django 3.2.12 on 2022-03-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imminent", "0002_earthquake"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdc",
            name="pdc_created_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="pdc created at"),
        ),
        migrations.AddField(
            model_name="pdc",
            name="pdc_updated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="pdc updated at"),
        ),
    ]
