# Generated by Django 3.2.16 on 2022-11-16 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_country_centroid'),
        ('imminent', '0005_pdc_severity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('hazard_type', models.CharField(blank=True, choices=[('EQ', 'Earthquake'), ('FL', 'Flood'), ('TC', 'Cyclone'), ('EP', 'Epidemic'), ('FI', 'Food Insecurity'), ('SS', 'Storm Surge'), ('DR', 'Drought'), ('TS', 'Tsunami'), ('CD', 'Cyclonic Wind')], max_length=100, verbose_name='Hazard type')),
                ('event_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Event id')),
                ('publish_date', models.DateTimeField(verbose_name='Publish_date')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.country', verbose_name='Country')),
            ],
        ),
    ]
