# Generated by Django 3.2.16 on 2022-11-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imminent", "0006_adam"),
    ]

    operations = [
        migrations.AddField(
            model_name="adam",
            name="geojson",
            field=models.JSONField(blank=True, null=True, verbose_name="GeJson"),
        ),
    ]
