# Generated by Django 3.2.17 on 2023-03-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imminent', '0009_adam_storm_position_geojson'),
    ]

    operations = [
        migrations.AddField(
            model_name='adam',
            name='population_exposure',
            field=models.JSONField(blank=True, null=True, verbose_name='Population Exposure'),
        ),
    ]
