# Generated by Django 3.2.17 on 2023-04-05 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20230206_0403'),
        ('imminent', '0011_auto_20230404_0400'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDACS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='start_date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='end_date')),
                ('hazard_id', models.CharField(max_length=255, verbose_name='hazard id')),
                ('hazard_name', models.CharField(max_length=255, verbose_name='hazard name')),
                ('hazard_type', models.CharField(blank=True, choices=[('EQ', 'Earthquake'), ('FL', 'Flood'), ('TC', 'Cyclone'), ('EP', 'Epidemic'), ('FI', 'Food Insecurity'), ('SS', 'Storm Surge'), ('DR', 'Drought'), ('TS', 'Tsunami'), ('CD', 'Cyclonic Wind'), ('WF', 'WildFire')], max_length=100, verbose_name='hazard type')),
                ('alert_level', models.CharField(blank=True, max_length=255, null=True, verbose_name='alert level')),
                ('footprint_geojson', models.JSONField(blank=True, null=True, verbose_name='GeJson')),
                ('event_details', models.JSONField(blank=True, null=True, verbose_name='Event Details')),
                ('population_exposure', models.JSONField(blank=True, null=True, verbose_name='Population Exposure')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.country', verbose_name='country')),
            ],
        ),
    ]
