# Generated by Django 3.2.17 on 2023-04-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imminent", "0012_gdacs"),
    ]

    operations = [
        migrations.AddField(
            model_name="gdacs",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="latitude"),
        ),
        migrations.AddField(
            model_name="gdacs",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="longitude"),
        ),
    ]
