# Generated by Django 3.2.17 on 2023-04-17 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0007_auto_20230206_0403"),
        ("imminent", "0013_auto_20230410_1021"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeteoSwiss",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("event_details", models.JSONField(blank=True, null=True, verbose_name="Event Details")),
                ("footprint_geojson", models.JSONField(blank=True, null=True, verbose_name="GeJson")),
                ("hazard_name", models.CharField(max_length=255, verbose_name="hazard name")),
                ("folder_id", models.CharField(max_length=255, verbose_name="folder id")),
                (
                    "hazard_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EQ", "Earthquake"),
                            ("FL", "Flood"),
                            ("TC", "Cyclone"),
                            ("EP", "Epidemic"),
                            ("FI", "Food Insecurity"),
                            ("SS", "Storm Surge"),
                            ("DR", "Drought"),
                            ("TS", "Tsunami"),
                            ("CD", "Cyclonic Wind"),
                            ("WF", "WildFire"),
                        ],
                        max_length=100,
                        verbose_name="hazard type",
                    ),
                ),
                ("initialization_date", models.DateField(verbose_name="initialization date")),
                ("event_date", models.DateField(verbose_name="event date")),
                ("impact_type", models.CharField(max_length=255, verbose_name="impact type")),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="common.country",
                        verbose_name="country",
                    ),
                ),
            ],
        ),
    ]
