# Generated by Django 3.2.17 on 2023-05-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imminent', '0015_meteoswissagg'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteoswissagg',
            name='geojson_details',
            field=models.JSONField(blank=True, null=True, verbose_name='Geojson Details'),
        ),
    ]
