# Generated by Django 3.2.17 on 2023-09-08 05:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('imminent', '0019_alter_meteoswissagg_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meteoswissagg',
            name='end_date',
        ),
        migrations.AddField(
            model_name='meteoswissagg',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meteoswiss',
            name='event_date',
            field=models.DateTimeField(verbose_name='event date'),
        ),
        migrations.AlterField(
            model_name='meteoswiss',
            name='initialization_date',
            field=models.DateTimeField(verbose_name='initialization date'),
        ),
        migrations.AlterField(
            model_name='meteoswissagg',
            name='start_date',
            field=models.DateTimeField(verbose_name='start date'),
        ),
    ]
