# Generated by Django 3.2.17 on 2023-09-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imminent', '0020_auto_20230908_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteoswiss',
            name='model_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='model name'),
        ),
        migrations.AddField(
            model_name='meteoswissagg',
            name='model_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='model name'),
        ),
    ]
