# Generated by Django 3.2.17 on 2024-09-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imminent", "0022_auto_20240809_0448"),
    ]

    operations = [
        migrations.AddField(
            model_name="gdacs",
            name="episode_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="hazard episode id"),
        ),
        migrations.AddField(
            model_name="pdc",
            name="stale_displacement",
            field=models.BooleanField(default=True, verbose_name="Requires displacement data update"),
        ),
    ]
