apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ifrcgo-risk-module.fullname" .}}-api-configmap
  labels:
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
data:
  # Application Info
  RISK_RELEASE: {{ .Values.image.tag | quote }}
  RISK_ENVIRONMENT: {{ .Values.environment | quote | upper }}
  RISK_API_FQDN: {{ required "env.RISK_API_FQDN" .Values.env.RISK_API_FQDN | quote }}
  # Django Configs
  DJANGO_DEBUG: {{ .Values.env.DJANGO_DEBUG | quote }}
  DJANGO_ALLOWED_HOSTS: {{ .Values.env.DJANGO_ALLOWED_HOSTS | quote }}
  TIME_ZONE: {{ .Values.env.TIME_ZONE | quote }}
  # Redis
  CACHE_REDIS_URL: {{ include "ifrcgo-risk-module.cacheRedisUrl" . | quote }}
  CELERY_REDIS_URL: {{ include "ifrcgo-risk-module.celeryRedisUrl" . | quote }}
  # Sentry
  SENTRY_TRACE_SAMPLE_RATE: {{ .Values.env.SENTRY_TRACE_SAMPLE_RATE | quote }}
  SENTRY_PROFILE_SAMPLE_RATE: {{ .Values.env.SENTRY_PROFILE_SAMPLE_RATE | quote }}
  # Logging
  APPS_LOGGING_LEVEL: {{ .Values.env.APPS_LOGGING_LEVEL | quote }}