apiVersion: v2

name: go-risk-module

description: A Helm chart for Kubernetes

type: application

version: 0.1.0

appVersion: "1.16.0"

dependencies:
  - name: postgresql
    version: 15.5.32
    condition: postgresql.enabled
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: 20.0.4
    condition: redis.enabled
    repository: https://charts.bitnami.com/bitnami