environment: sandbox

image:
  repository: ghcr.io/ifrcgo/go-risk-module-api
  pullPolicy: Always
  tag: "test"

nameOverride: ""
fullnameOverride: ""

imagePullSecrets:
  - name: ghcr-secret

env:
  APPS_LOGGING_LEVEL: "WARNING"
  DATABASE_HOST:
  DATABASE_NAME:
  DATABASE_PORT: 5432
  DATABASE_USER:
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_DEBUG: "True"
  METEOSWISS_S3_BUCKET: some-bucket
  METEOSWISS_S3_ENDPOINT_URL: "https://s3.amazonaws.com"
  RISK_API_FQDN: "go-risk-module.ifrc.org"
  SENTRY_TRACE_SAMPLE_RATE: "0.2"
  SENTRY_PROFILE_SAMPLE_RATE: "0.2"
  TIME_ZONE: "UTC"

secrets:
  name: ""
  keys:
    - DATABASE_NAME
    - DATABASE_HOST
    - DATABASE_PASSWORD
    - DATABASE_PORT
    - DATABASE_USER
    - DJANGO_SECRET_KEY
    - METEOSWISS_S3_BUCKET
    - METEOSWISS_S3_ENDPOINT_URL
    - METEOSWISS_S3_ACCESS_KEY
    - METEOSWISS_S3_BUCKET
    - METEOSWISS_S3_SECRET_KEY
    - PDC_ACCESS_TOKEN
    - PDC_PASSWORD
    - PDC_USERNAME
    - SENTRY_DSN

api:
  enabled: true
  containerPort: 9001
  ingress:
    enabled: true
    host: go-risk-test.ifrc.org
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 500Mi

celery:
  resources: {}

celeryBeat:
  resources: {}

# Subchart configuration
postgresql:
  enabled: true
  fullnameOverride: ""

redis:
  enabled: true
  auth:
    enabled: false
  architecture: standalone
  fullnameOveride: ""
  replica:
    replicaCount: 0

# Global configurations are required for consistency across the chart and its subcharts
global:
  postgresql:
    auth:
      username: ""
      database: ""
      existingSecret: my-risk-module-secret
      secretKeys:
        userPasswordKey: DATABASE_PASSWORD
        adminPasswordKey: DATABASE_PASSWORD
    service:
      ports:
        postgresql: 5432

azure:
  aksSecretsProviderAvailable: true
  keyvault:
    name: risk-module-playground-k
    clientId: "1d64d996-002b-47c0-ad1f-b2a400d83d5c"
    tenantId: "a2b53be5-734e-4e6c-ab0d-d184f60fd917"

serviceAccount:
  # Specifies whether a service account should be created
  # Required when using workload identity to access Azure Key Vault Secrets
  create: true
  automount: true
  annotations:
    azure.workload.identity/client-id : "1d64d996-002b-47c0-ad1f-b2a400d83d5c"
  labels:
    azure.workload.identity/use: "true"
  name: "service-token-reader"

worker:
  enabled: true
  defaultResources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 2Gi
  # NOTE: Application level configuration
  cronjobs:
    "import_earthquake_data":
      schedule: "0 0 * * *"
      enabled: true
      # timeLimit: 7200
    "create_pdc_data":
      schedule: "0 */2 * * *"
      enabled: true
    "create_pdc_daily":
      schedule: "0 5 * * *"
      enabled: true
    "create_pdc_displacement":
      schedule: "0 */3 * * *"
      enabled: true
    "create_pdc_polygon":
      schedule: "0 */6 * * *"
      enabled: true
    "create_pdc_intensity":
      schedule: "0 */7 * * *"
      enabled: true
    "check_pdc_status":
      schedule: "0 1 * * *"
      enabled: true
    "create_hazard_information":
      schedule: "0 0 2 * *"
      enabled: true
    "create_adam_exposure":
      schedule: "0 */4 * * *"
      enabled: true
    "update_adam_cyclone":
      schedule: "0 */4 * * *"
      enabled: true
    "update_adam_alert_level":
      schedule: "0 */4 * * *"
      enabled: true
    "import_gdacs_data":
      schedule: "0 */4 * * *"
      enabled: true
    "pull_meteoswiss":
      schedule: "0 */4 * * *"
      enabled: true
    "pull_meteoswiss_geo":
      schedule: "0 */4 * * *"
      enabled: true
    "meteoswiss_agg":
      schedule: "0 */4 * * *"
      enabled: true