image:
  repository: ghcr.io/ifrcgo/go-risk-module-api
  pullPolicy: IfNotPresent
  tag: "test"

nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []


appConfig:
  DJANGO_DEBUG: ""
  METEOSWISS_S3_BUCKET: ""
  METEOSWISS_S3_ENDPOINT_URL: ""
  PDC_USERNAME: ""
  RISK_ENVIRONMENT: ""
  RISK_API_FQDN: ""

appSecret:
  name: ""
  keys:
    - DATABASE_PASSWORD
    - DJANGO_SECRET_KEY
    - METEOSWISS_S3_ACCESS_KEY
    - METEOSWISS_S3_BUCKET
    - METEOSWISS_S3_SECRET_KEY
    - PDC_ACCESS_TOKEN
    - PDC_PASSWORD

api:
  resources: {}

celery:
  resources: {}

celeryBeat:
  resources: {}

# Subchart configuration
postgresql:
  enabled: true
  fullnameOverride: ""

redis:
  enabled: true
  auth:
    enabled: false
  architecture: standalone
  replica:
    replicaCount: 0

# Global configurations are required for consistency across the chart and its subcharts
global:
  postgresql:
    auth:
      username: ""
      database: ""
      existingSecret: "<insert_application_secret_name_here"
      secretKeys:
        userPasswordKey: DATABASE_PASSWORD
        adminPasswordKey: DATABASE_PASSWORD
    service:
      ports:
        postgresql: 5432

# Connection parameters for external PostgreSQL database
externalDatabase:
  host: ""
  port: 5432
  auth:
    username:
    database:
    existingSecret:
    secretKeys:
      userPasswordKey:

# Connection parameters for external Redis
externalRedis:
  host: ""
  port: 6379

azure:
  aksSecretsProviderAvailable: true
  keyvault:
    name: ""
    clientId: ""
    tenantId: ""

serviceAccount:
  # Specifies whether a service account should be created
  # Required when using workload identity to access Azure Key Vault Secrets
  create: true
  automount: true
  annotations:
    azure.workload.identity/client-id : "<workload_identity_client_id>"
  labels:
    azure.workload.identity/use: "true"
  name: ""