name: Build and Push Docker Image

on:
  push:
    branches: 
      - feature/helm-chart

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: 🐳 Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: 🐳 Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ github.ref }}
          ${{ runner.os }}-buildx-

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/ifrcgo/go-risk-module-api:${{ github.sha }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.10.0

    - name: Update Helm chart version and appVersion
      run: |
        sed -i 's/version:.*/version: ${{ github.ref_name }}/' helm/go-risk-api/Chart.yaml
        sed -i 's/appVersion:.*/appVersion: ${{ github.ref_name }}/' helm/go-risk-api/Chart.yaml

    - name: Update Helm chart image
      run: |
        sed -i 's|repository:.*|repository: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}|' helm/go-risk-api/values.yaml
        sed -i 's/tag:.*/tag: ${{ github.ref_name }}/' helm/go-risk-api/values.yaml

    - name: Package Helm chart
      run: helm package helm

    - name: Publish Helm chart
      run: |
        helm plugin install https://github.com/chartmuseum/helm-push
        helm repo add --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} chartrepo ${{ env.REGISTRY }}/${{ github.repository_owner }}/charts
        helm cm-push ${{ github.event.repository.name }}-${{ github.ref_name }}.tgz chartrepo