name: Python linter

on:
  push:
    branches:
      - develop
  pull_request:


jobs:
  pre_commit_checks:
    name: 🚴 Pre-Commit checks 🚴
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: gdal-bin libgdal-dev

      - name: Setup uv python environment
        run: uv venv

      - name: uv lock check
        run: uv lock --locked --offline

      - name: uv sync
        run: uv sync --all-extras

      - uses: pre-commit/action@main
